<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use Illuminate\Support\Carbon;

class CodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
public function run(): void
    {
        // Truncate the table
        DB::table('codes')->truncate();

        $now = Carbon::now();
        DB::table('codes')->insert([
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'dashboard',
                'value1'     => 'Dashboard',
                'value2'     => null,
                'order_no'   => 1,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],             
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'users',
                'value1'     => 'Users',
                'value2'     => null,
                'order_no'   => 2,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'permissions',
                'value1'     => 'Permissions',
                'value2'     => null,
                'order_no'   => 3,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'roles',
                'value1'     => 'Roles',
                'value2'     => null,
                'order_no'   => 4,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'menus',
                'value1'     => 'Menus',
                'value2'     => null,
                'order_no'   => 5,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'codes',
                'value1'     => 'Codes',
                'value2'     => null,
                'order_no'   => 6,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'MODULE_NAME',
                'code'       => 'products',
                'value1'     => 'Products',
                'value2'     => null,
                'order_no'   => 7,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_DATA_TYPE',
                'code'       => 'STRING',
                'value1'     => 'STRING',
                'value2'     => null,
                'order_no'   => 1,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_DATA_TYPE',
                'code'       => 'NUMBER',
                'value1'     => 'NUMBER',
                'value2'     => null,
                'order_no'   => 2,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_DATA_TYPE',
                'code'       => 'CURRENCY',
                'value1'     => 'CURRENCY',
                'value2'     => null,
                'order_no'   => 3,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ], 
            [
                'code_group' => 'REPORT_DATA_TYPE',
                'code'       => 'DATE',
                'value1'     => 'DATE',
                'value2'     => null,
                'order_no'   => 4,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_DATA_TYPE',
                'code'       => 'DATETIME',
                'value1'     => 'DATETIME',
                'value2'     => null,
                'order_no'   => 5,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'STRING',
                'value1'     => 'STRING',
                'value2'     => null,
                'order_no'   => 1,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'NUMBER',
                'value1'     => 'NUMBER',
                'value2'     => null,
                'order_no'   => 2,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'CURRENCY',
                'value1'     => 'CURRENCY',
                'value2'     => null,
                'order_no'   => 3,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'COMBOBOX',
                'value1'     => 'COMBOBOX',
                'value2'     => null,
                'order_no'   => 4,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'DATE',
                'value1'     => 'DATE',
                'value2'     => null,
                'order_no'   => 5,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'DATETIME',
                'value1'     => 'DATETIME',
                'value2'     => null,
                'order_no'   => 6,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_PARAMETER_TYPE',
                'code'       => 'HIDDEN',
                'value1'     => 'HIDDEN',
                'value2'     => null,
                'order_no'   => 7,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_ALIGN',
                'code'       => 'LEFT',
                'value1'     => 'LEFT',
                'value2'     => null,
                'order_no'   => 1,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],        
            [
                'code_group' => 'REPORT_ALIGN',
                'code'       => 'CENTER',
                'value1'     => 'CENTER',
                'value2'     => null,
                'order_no'   => 2,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'REPORT_ALIGN',
                'code'       => 'RIGHT',
                'value1'     => 'RIGHT',
                'value2'     => null,
                'order_no'   => 3,
                'tag1'       => null,
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'DATASOURCE',
                'code'       => 'REPORT',
                'value1'     => 'REPORT',
                'value2'     => 'SELECT name, id as code FROM reports where deleted_at is null and is_active = 1',
                'order_no'   => 1,
                'tag1'       => 'QUERY',
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],                           
            [
                'code_group' => 'DATASOURCE',
                'code'       => 'CUSTOMER',
                'value1'     => 'CUSTOMER',
                'value2'     => 'SELECT name as label, id as value FROM customers where deleted_at is null',
                'order_no'   => 2,
                'tag1'       => 'QUERY',
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'DATASOURCE',
                'code'       => 'PRODUCT',
                'value1'     => 'PRODUCT',
                'value2'     => 'SELECT name as label, id as value FROM products where deleted_at is null and is_active = 1',
                'order_no'   => 3,
                'tag1'       => 'QUERY',
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code_group' => 'DATASOURCE',
                'code'       => 'ITEM_PRODUCT',
                'value1'     => 'ITEM_PRODUCT',
                'value2'     => 'SELECT name as label, id as value FROM item_products where deleted_at is null',
                'order_no'   => 2,
                'tag1'       => 'QUERY',
                'tag2'       => null,
                'tag3'       => null,
                'is_active'  => true,
                'updated_by' => 'SYSTEM',
                'created_by' => 'SYSTEM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
        ]);
    }
}
